### ISSUE TITLE
Sanitization extension methods are wrong

### ISSUE THREAD

**Issue by uwx** [Naamloos/ModCore#77]
The following methods will never be called without a cast:

https://github.com/NaamloosDT/ModCore/blob/8f47918d6273b2b9c4efa8dea360e2ba2a7369ed/ModCore/Logic/Extensions/Sanitization.cs#L29-L39

This is due to an intricacy in how overload resolution works in the C# compiler, it will always prefer the `string` overload over the `FormattableString` one.

The only fix is to rename these overloads and use them wherever appropriate. They should probably not be removed, as they enforce invariant culture and sanitization within interpolated string parameters, which is pretty important.

**Comment by Naamloos** [comment]
I renamed the unformatted methods to `DoStuffUnformattedAsync`. Could've done it the other way around (would've meant I didn't have to rename 90-ish appearances) but whatever. Gets fixed in next commit.

It also seems like the FormattableString doesn't allow the primary string type to be givin in it's place, is that intentional?

On another note the Formatted versions of the methods don't seem to be used anywhere.

**Comment by Naamloos** [comment]
eh, suppose it's ok now. Feel free to reopen if my mix sucked ass.
